# Codecov Configuration
# Docs: https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
        base: auto
    patch:
      default:
        target: auto
        threshold: 0.5%
        base: auto

  range: 50..100
  round: down
  precision: 2

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/*.config.ts"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/.next/**"
  - "**/coverage/**"
  - "**/tests/**"
  - "**/fixtures/**"
  - "**/__tests__/**"
  - "**/*.d.ts"
  - "**/scripts/**"
  - "**/migrations/**"

# GitHub Checks
github_checks:
  annotations: true

# Pull Request behavior
pull_request_settings:
  enabled: yes
  require_codecov_approver_to_proceed: no
  require_number_of_pr_reviewers: 0
  require_ci_to_pass: no
