#!/bin/bash

# 🚀 Deploy Manual no Render - Guia Passo a Passo
# 
# Como este script NÃO tem acesso à Render API Key, o deploy deve ser feito manualmente.
# Siga os passos abaixo:

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 DEPLOY MANUAL NO RENDER - QIVO MINING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📦 Commits prontos para deploy:"
echo "   • 498a55d - 🧪 Test: Script de validação do cache fix"
echo "   • b6bdccd - 🔧 Fix: Cache agressivo corrigido"
echo "   • c45d7f6 - ⚡ Perf: Otimiza polling auditoria"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "PASSO 1: Acessar Render Dashboard"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   1. Abra seu navegador"
echo "   2. Acesse: https://dashboard.render.com"
echo "   3. Faça login com suas credenciais"
echo "   4. Clique no serviço: 'qivo-mining'"
echo ""
echo "   Ou acesse diretamente:"
echo "   👉 https://dashboard.render.com/web/srv-d3sk5h1r0fns738ibdg0"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "PASSO 2: Iniciar Deploy Manual"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   1. Na página do serviço, clique em 'Manual Deploy' (botão azul)"
echo "   2. Selecione: 'Deploy latest commit'"
echo "   3. Confirme o deploy"
echo ""
echo "   Ou use o botão direto:"
echo "   👉 [Manual Deploy] → [Deploy latest commit]"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "PASSO 3: Aguardar Build (3-5 minutos)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   O build deve seguir estas etapas:"
echo ""
echo "   1. Cloning repository..."
echo "   2. Installing pnpm..."
echo "   3. Running build command:"
echo "      • npm install -g pnpm@latest"
echo "      • pnpm install"
echo "      • pnpm run build"
echo "   4. Starting service..."
echo "      • pnpm start"
echo ""
echo "   Monitore os logs em tempo real:"
echo "   👉 https://dashboard.render.com/web/srv-d3sk5h1r0fns738ibdg0/logs"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "PASSO 4: Validar Deploy"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Após deploy concluído, execute:"
echo ""
echo "   bash scripts/test-cache-fix.sh"
echo ""
echo "   Esperado:"
echo "   ✅ Service Worker na versão: qivo-v1.2.1-fix"
echo "   ✅ Headers anti-cache em JS/CSS"
echo "   ✅ Umami desabilitado"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "PASSO 5: Testar no Navegador"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   1. Abra: https://qivo-mining.onrender.com"
echo "   2. Abra DevTools (F12)"
echo "   3. Application → Storage → Clear site data"
echo "   4. Service Workers → Unregister all"
echo "   5. Hard reload (Ctrl+Shift+R ou Cmd+Shift+R)"
echo "   6. Console deve mostrar:"
echo "      [SW] Install event - Version: qivo-v1.2.1-fix"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "PASSO 6 (OPCIONAL): Habilitar Auto-Deploy"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Para deploys automáticos a cada push:"
echo ""
echo "   1. Editar render.yaml localmente:"
echo "      autoDeploy: false  →  autoDeploy: true"
echo ""
echo "   2. Commit e push:"
echo "      git add render.yaml"
echo "      git commit -m 'chore: Habilita auto-deploy'"
echo "      git push origin main"
echo ""
echo "   3. Ou editar no Dashboard:"
echo "      Settings → Build & Deploy → Auto-Deploy: ON"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 DOCUMENTAÇÃO COMPLETA"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   • Guia Completo: docs/CACHE_FIX_GUIDE.md"
echo "   • Resumo Executivo: CACHE_FIX_SUMMARY.md"
echo "   • Script de Teste: scripts/test-cache-fix.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 CHECKLIST DE DEPLOY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   [ ] Acessar Render Dashboard"
echo "   [ ] Clicar em 'Manual Deploy'"
echo "   [ ] Aguardar build completar (3-5 min)"
echo "   [ ] Verificar logs sem erros"
echo "   [ ] Executar: bash scripts/test-cache-fix.sh"
echo "   [ ] Testar no navegador (limpar cache)"
echo "   [ ] Verificar console: Service Worker v1.2.1-fix"
echo "   [ ] Confirmar módulo de auditoria rápido"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚨 SE HOUVER PROBLEMAS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Rollback para versão anterior:"
echo ""
echo "   1. Dashboard → Deploys → Histórico"
echo "   2. Encontrar deploy 106b636 (versão estável anterior)"
echo "   3. Clicar em 'Redeploy'"
echo ""
echo "   Ou via terminal:"
echo "   git reset --hard 106b636"
echo "   git push origin main --force"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ TUDO PRONTO! Agora é só seguir os passos acima."
echo ""
echo "💡 Dica: Abra este guia em uma aba e o Render Dashboard em outra."
echo ""
echo "🔗 Links Rápidos:"
echo "   • Dashboard: https://dashboard.render.com"
echo "   • Serviço: https://dashboard.render.com/web/srv-d3sk5h1r0fns738ibdg0"
echo "   • Logs: https://dashboard.render.com/web/srv-d3sk5h1r0fns738ibdg0/logs"
echo "   • App: https://qivo-mining.onrender.com"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
