/**
 * Internationalization (i18n) for Technical Reports
 * 
 * Provides translations for report generation, export, and rendering.
 * Supports: pt-BR, en-US, es-ES, fr-FR
 * 
 * @module i18n
 * @sprint SPRINT5-FIX
 */

export type SupportedLanguage = 'pt-BR' | 'en-US' | 'es-ES' | 'fr-FR';

export interface ReportTranslations {
  // Document titles and headers
  technicalReport: string;
  reportTitle: string;
  generatedBy: string;
  generatedOn: string;
  version: string;
  standard: string;
  
  // Common sections
  executiveSummary: string;
  introduction: string;
  methodology: string;
  results: string;
  conclusions: string;
  recommendations: string;
  references: string;
  appendices: string;
  
  // JORC specific
  samplingAndData: string;
  explorationResults: string;
  mineralResources: string;
  oreReserves: string;
  
  // NI 43-101 specific
  summary: string;
  propertyDescription: string;
  geology: string;
  mineralization: string;
  
  // Common fields
  projectName: string;
  location: string;
  date: string;
  author: string;
  company: string;
  competentPerson: string;
  
  // Export formats
  exportPdf: string;
  exportDocx: string;
  exportXlsx: string;
  
  // Status and messages
  draft: string;
  underReview: string;
  approved: string;
  page: string;
  of: string;
  
  // Table headers
  item: string;
  description: string;
  value: string;
  unit: string;
  notes: string;
}

/**
 * Translation dictionary for all supported languages
 */
const translations: Record<SupportedLanguage, ReportTranslations> = {
  'pt-BR': {
    technicalReport: 'Relatório Técnico',
    reportTitle: 'Título do Relatório',
    generatedBy: 'Gerado por',
    generatedOn: 'Gerado em',
    version: 'Versão',
    standard: 'Padrão',
    
    executiveSummary: 'Sumário Executivo',
    introduction: 'Introdução',
    methodology: 'Metodologia',
    results: 'Resultados',
    conclusions: 'Conclusões',
    recommendations: 'Recomendações',
    references: 'Referências',
    appendices: 'Apêndices',
    
    samplingAndData: 'Amostragem e Dados',
    explorationResults: 'Resultados de Exploração',
    mineralResources: 'Recursos Minerais',
    oreReserves: 'Reservas de Minério',
    
    summary: 'Resumo',
    propertyDescription: 'Descrição da Propriedade',
    geology: 'Geologia',
    mineralization: 'Mineralização',
    
    projectName: 'Nome do Projeto',
    location: 'Localização',
    date: 'Data',
    author: 'Autor',
    company: 'Empresa',
    competentPerson: 'Pessoa Competente',
    
    exportPdf: 'Exportar PDF',
    exportDocx: 'Exportar Word',
    exportXlsx: 'Exportar Excel',
    
    draft: 'Rascunho',
    underReview: 'Em Revisão',
    approved: 'Aprovado',
    page: 'Página',
    of: 'de',
    
    item: 'Item',
    description: 'Descrição',
    value: 'Valor',
    unit: 'Unidade',
    notes: 'Notas',
  },
  
  'en-US': {
    technicalReport: 'Technical Report',
    reportTitle: 'Report Title',
    generatedBy: 'Generated by',
    generatedOn: 'Generated on',
    version: 'Version',
    standard: 'Standard',
    
    executiveSummary: 'Executive Summary',
    introduction: 'Introduction',
    methodology: 'Methodology',
    results: 'Results',
    conclusions: 'Conclusions',
    recommendations: 'Recommendations',
    references: 'References',
    appendices: 'Appendices',
    
    samplingAndData: 'Sampling and Data',
    explorationResults: 'Exploration Results',
    mineralResources: 'Mineral Resources',
    oreReserves: 'Ore Reserves',
    
    summary: 'Summary',
    propertyDescription: 'Property Description',
    geology: 'Geology',
    mineralization: 'Mineralization',
    
    projectName: 'Project Name',
    location: 'Location',
    date: 'Date',
    author: 'Author',
    company: 'Company',
    competentPerson: 'Competent Person',
    
    exportPdf: 'Export PDF',
    exportDocx: 'Export Word',
    exportXlsx: 'Export Excel',
    
    draft: 'Draft',
    underReview: 'Under Review',
    approved: 'Approved',
    page: 'Page',
    of: 'of',
    
    item: 'Item',
    description: 'Description',
    value: 'Value',
    unit: 'Unit',
    notes: 'Notes',
  },
  
  'es-ES': {
    technicalReport: 'Informe Técnico',
    reportTitle: 'Título del Informe',
    generatedBy: 'Generado por',
    generatedOn: 'Generado en',
    version: 'Versión',
    standard: 'Estándar',
    
    executiveSummary: 'Resumen Ejecutivo',
    introduction: 'Introducción',
    methodology: 'Metodología',
    results: 'Resultados',
    conclusions: 'Conclusiones',
    recommendations: 'Recomendaciones',
    references: 'Referencias',
    appendices: 'Apéndices',
    
    samplingAndData: 'Muestreo y Datos',
    explorationResults: 'Resultados de Exploración',
    mineralResources: 'Recursos Minerales',
    oreReserves: 'Reservas de Mineral',
    
    summary: 'Resumen',
    propertyDescription: 'Descripción de la Propiedad',
    geology: 'Geología',
    mineralization: 'Mineralización',
    
    projectName: 'Nombre del Proyecto',
    location: 'Ubicación',
    date: 'Fecha',
    author: 'Autor',
    company: 'Empresa',
    competentPerson: 'Persona Competente',
    
    exportPdf: 'Exportar PDF',
    exportDocx: 'Exportar Word',
    exportXlsx: 'Exportar Excel',
    
    draft: 'Borrador',
    underReview: 'En Revisión',
    approved: 'Aprobado',
    page: 'Página',
    of: 'de',
    
    item: 'Artículo',
    description: 'Descripción',
    value: 'Valor',
    unit: 'Unidad',
    notes: 'Notas',
  },
  
  'fr-FR': {
    technicalReport: 'Rapport Technique',
    reportTitle: 'Titre du Rapport',
    generatedBy: 'Généré par',
    generatedOn: 'Généré le',
    version: 'Version',
    standard: 'Norme',
    
    executiveSummary: 'Résumé Exécutif',
    introduction: 'Introduction',
    methodology: 'Méthodologie',
    results: 'Résultats',
    conclusions: 'Conclusions',
    recommendations: 'Recommandations',
    references: 'Références',
    appendices: 'Annexes',
    
    samplingAndData: 'Échantillonnage et Données',
    explorationResults: "Résultats d'Exploration",
    mineralResources: 'Ressources Minérales',
    oreReserves: 'Réserves de Minerai',
    
    summary: 'Résumé',
    propertyDescription: 'Description de la Propriété',
    geology: 'Géologie',
    mineralization: 'Minéralisation',
    
    projectName: 'Nom du Projet',
    location: 'Emplacement',
    date: 'Date',
    author: 'Auteur',
    company: 'Entreprise',
    competentPerson: 'Personne Compétente',
    
    exportPdf: 'Exporter PDF',
    exportDocx: 'Exporter Word',
    exportXlsx: 'Exporter Excel',
    
    draft: 'Brouillon',
    underReview: 'En Révision',
    approved: 'Approuvé',
    page: 'Page',
    of: 'de',
    
    item: 'Article',
    description: 'Description',
    value: 'Valeur',
    unit: 'Unité',
    notes: 'Notes',
  },
};

/**
 * Get translations for a specific language
 * 
 * @param language - The target language code
 * @returns Translation object for the language
 */
export function getTranslations(language: SupportedLanguage = 'pt-BR'): ReportTranslations {
  return translations[language] || translations['pt-BR'];
}

/**
 * Translate a specific key to target language
 * 
 * @param key - The translation key
 * @param language - The target language code
 * @returns Translated string
 */
export function translate(key: keyof ReportTranslations, language: SupportedLanguage = 'pt-BR'): string {
  const t = getTranslations(language);
  return t[key] || key;
}

/**
 * Get language display name with flag emoji
 * 
 * @param language - The language code
 * @returns Display name with flag
 */
export function getLanguageDisplay(language: SupportedLanguage): string {
  const displays: Record<SupportedLanguage, string> = {
    'pt-BR': '🇧🇷 Português (Brasil)',
    'en-US': '🇺🇸 English (US)',
    'es-ES': '🇪🇸 Español',
    'fr-FR': '🇫🇷 Français',
  };
  return displays[language] || displays['pt-BR'];
}

/**
 * Detect language from report metadata
 * 
 * @param metadata - Report metadata object
 * @returns Detected language or default
 */
export function detectLanguageFromMetadata(metadata: any): SupportedLanguage {
  if (!metadata) return 'pt-BR';
  
  const lang = metadata.language || metadata.lang || metadata.locale;
  
  if (lang && ['pt-BR', 'en-US', 'es-ES', 'fr-FR'].includes(lang)) {
    return lang as SupportedLanguage;
  }
  
  return 'pt-BR';
}

/**
 * Format date according to language locale
 * 
 * @param date - Date to format
 * @param language - Target language
 * @returns Formatted date string
 */
export function formatDate(date: Date | string, language: SupportedLanguage = 'pt-BR'): string {
  const dateObj = typeof date === 'string' ? new Date(date) : date;
  
  const locales: Record<SupportedLanguage, string> = {
    'pt-BR': 'pt-BR',
    'en-US': 'en-US',
    'es-ES': 'es-ES',
    'fr-FR': 'fr-FR',
  };
  
  return dateObj.toLocaleDateString(locales[language], {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

export default {
  getTranslations,
  translate,
  getLanguageDisplay,
  detectLanguageFromMetadata,
  formatDate,
};
