/**
 * SEC S-K 1300 Schema
 * Securities and Exchange Commission - Regulation S-K Item 1300
 * Mining Property Disclosure Requirements (Effective February 25, 2019)
 */

import type { FieldDefinition, StandardSchema } from './standardSchemasExpanded';

export const SEC_SK_1300_SCHEMA: StandardSchema = {
  code: 'SEC_SK_1300',
  name: 'SEC S-K 1300',
  description: 'U.S. Securities and Exchange Commission Mining Property Disclosure',
  sections: [
    // Basic Information
    {
      title: 'Basic Information',
      fields: [
        {
          name: 'title',
          label: 'Report Title',
          type: 'text',
          required: true,
          placeholder: 'Ex: Technical Report Summary - Copper Mountain Mine',
          helpText: 'Minimum 5 characters. Be specific for easy identification.',
          gridColumn: 'full',
        },
        {
          name: 'registrantName',
          label: 'Registrant Name',
          type: 'text',
          required: true,
          placeholder: 'Ex: Copper Mountain Mining Corporation',
          gridColumn: '1',
        },
        {
          name: 'ticker',
          label: 'Stock Ticker',
          type: 'text',
          required: true,
          placeholder: 'Ex: CMMC',
          helpText: 'Stock exchange ticker symbol',
          gridColumn: '2',
        },
        {
          name: 'exchange',
          label: 'Stock Exchange',
          type: 'select',
          required: true,
          options: [
            { value: 'NYSE', label: 'New York Stock Exchange (NYSE)' },
            { value: 'NASDAQ', label: 'NASDAQ' },
            { value: 'TSX', label: 'Toronto Stock Exchange (TSX)' },
            { value: 'TSX-V', label: 'TSX Venture Exchange' },
            { value: 'ASX', label: 'Australian Securities Exchange' },
            { value: 'LSE', label: 'London Stock Exchange' },
          ],
          gridColumn: '1',
        },
        {
          name: 'effectiveDate',
          label: 'Effective Date',
          type: 'date',
          required: true,
          helpText: 'Date of report effectiveness',
          gridColumn: '2',
        },
      ],
    },

    // Item 1301 - Property Description and Location
    {
      title: 'Item 1301 - Property Description and Location',
      description: 'Description and location of the registrant\'s material properties',
      fields: [
        {
          name: 'propertyName',
          label: 'Property Name',
          type: 'text',
          required: true,
          placeholder: 'Ex: Copper Mountain Mine',
          helpText: 'Official name of the mining property',
          gridColumn: '1',
        },
        {
          name: 'propertyLocation',
          label: 'Property Location',
          type: 'text',
          required: true,
          placeholder: 'Ex: Princeton, British Columbia, Canada',
          helpText: 'Geographic location with state/province and country',
          gridColumn: '2',
        },
        {
          name: 'coordinates',
          label: 'Geographic Coordinates',
          type: 'text',
          required: true,
          placeholder: 'Ex: 49°20\'N, 120°35\'W',
          helpText: 'Latitude and longitude in decimal degrees or DMS',
          gridColumn: 'full',
        },
        {
          name: 'propertySize',
          label: 'Property Size (acres)',
          type: 'number',
          required: true,
          helpText: 'Total property area in acres',
          gridColumn: '1',
        },
        {
          name: 'propertySizeHectares',
          label: 'Property Size (hectares)',
          type: 'number',
          required: false,
          helpText: 'Total property area in hectares (optional)',
          gridColumn: '2',
        },
        {
          name: 'accessDescription',
          label: 'Access and Infrastructure',
          type: 'textarea',
          required: true,
          placeholder: 'Describe roads, power lines, water sources, proximity to towns...',
          helpText: 'Description of access routes, power, water, and infrastructure',
          gridColumn: 'full',
        },
        {
          name: 'climate',
          label: 'Climate and Operating Season',
          type: 'textarea',
          required: true,
          placeholder: 'Describe climate conditions, annual precipitation, operating season...',
          helpText: 'Describe climate conditions and impact on operations',
          gridColumn: 'full',
        },
        {
          name: 'physiography',
          label: 'Physiography',
          type: 'textarea',
          required: true,
          placeholder: 'Describe topography, elevation range, vegetation...',
          helpText: 'Description of topography and physical features',
          gridColumn: 'full',
        },
      ],
    },

    // Item 1302 - Property Ownership
    {
      title: 'Item 1302 - Property Ownership',
      description: 'Information about property ownership and agreements',
      fields: [
        {
          name: 'ownershipType',
          label: 'Ownership Type',
          type: 'select',
          required: true,
          options: [
            { value: 'fee_simple', label: 'Fee Simple (Freehold)' },
            { value: 'leasehold', label: 'Leasehold' },
            { value: 'concession', label: 'Mining Concession' },
            { value: 'patented_claim', label: 'Patented Mining Claim' },
            { value: 'unpatented_claim', label: 'Unpatented Mining Claim' },
            { value: 'exploration_license', label: 'Exploration License' },
            { value: 'mining_license', label: 'Mining License' },
          ],
          gridColumn: '1',
        },
        {
          name: 'ownershipPercentage',
          label: 'Registrant Ownership (%)',
          type: 'number',
          required: true,
          placeholder: 'Ex: 100',
          helpText: 'Percentage owned or controlled by registrant',
          gridColumn: '2',
        },
        {
          name: 'ownershipDetails',
          label: 'Ownership Details',
          type: 'textarea',
          required: true,
          placeholder: 'Describe ownership structure, agreements, partners, terms...',
          helpText: 'Describe ownership structure, agreements, and terms',
          gridColumn: 'full',
        },
        {
          name: 'royalties',
          label: 'Royalties and Encumbrances',
          type: 'textarea',
          required: true,
          placeholder: 'List NSR royalties, liens, encumbrances, payment terms...',
          helpText: 'List all royalties, liens, and encumbrances with rates and terms',
          gridColumn: 'full',
        },
        {
          name: 'permitsRequired',
          label: 'Required Permits and Status',
          type: 'textarea',
          required: true,
          placeholder: 'List mining permit, water rights, environmental permits, status...',
          helpText: 'List all required permits and their current status',
          gridColumn: 'full',
        },
        {
          name: 'permitsInGoodStanding',
          label: 'Permits in Good Standing',
          type: 'select',
          required: true,
          options: [
            { value: 'yes', label: 'Yes - All permits current and valid' },
            { value: 'no', label: 'No - Some permits expired or pending' },
            { value: 'partial', label: 'Partial - Some permits pending renewal' },
          ],
          gridColumn: '1',
        },
      ],
    },

    // Item 1303 - Material Agreements
    {
      title: 'Item 1303 - Material Agreements',
      description: 'Agreements affecting the property rights',
      fields: [
        {
          name: 'hasAgreements',
          label: 'Material Agreements Exist?',
          type: 'select',
          required: true,
          options: [
            { value: 'yes', label: 'Yes' },
            { value: 'no', label: 'No' },
          ],
          gridColumn: '1',
        },
        {
          name: 'agreementsList',
          label: 'Material Agreements',
          type: 'textarea',
          required: false,
          placeholder: 'List earn-in agreements, joint ventures, option agreements, offtake agreements...',
          helpText: 'List all material agreements (earn-in, joint venture, option, offtake, etc.)',
          gridColumn: 'full',
        },
        {
          name: 'agreementTerms',
          label: 'Agreement Terms and Conditions',
          type: 'textarea',
          required: false,
          placeholder: 'Summarize key terms, payment obligations, work commitments...',
          helpText: 'Summarize key terms, conditions, and obligations',
          gridColumn: 'full',
        },
      ],
    },

    // Item 1304 - Exploration History
    {
      title: 'Item 1304 - Exploration History',
      description: 'Historical and recent exploration activities',
      fields: [
        {
          name: 'historicalExploration',
          label: 'Historical Exploration',
          type: 'textarea',
          required: true,
          placeholder: 'Summarize exploration by previous operators, significant discoveries...',
          helpText: 'Summary of historical exploration activities prior to registrant',
          gridColumn: 'full',
        },
        {
          name: 'recentExploration',
          label: 'Recent Exploration (Last 5 Years)',
          type: 'textarea',
          required: true,
          placeholder: 'Describe drilling programs, geophysical surveys, assay results...',
          helpText: 'Detailed description of recent exploration work by registrant',
          gridColumn: 'full',
        },
        {
          name: 'explorationBudget',
          label: 'Exploration Budget ($)',
          type: 'number',
          required: false,
          placeholder: 'Ex: 5000000',
          helpText: 'Estimated or actual exploration expenditure',
          gridColumn: '1',
        },
        {
          name: 'drillingCompleted',
          label: 'Total Drilling Completed (meters)',
          type: 'number',
          required: false,
          placeholder: 'Ex: 25000',
          helpText: 'Cumulative drilling to date',
          gridColumn: '2',
        },
      ],
    },

    // Item 1305 - Environmental Considerations
    {
      title: 'Item 1305 - Environmental Considerations',
      description: 'Environmental aspects and regulatory compliance',
      fields: [
        {
          name: 'environmentalPermits',
          label: 'Environmental Permits',
          type: 'textarea',
          required: true,
          placeholder: 'List Clean Water Act permits, air quality permits, state permits...',
          helpText: 'List all environmental permits and status',
          gridColumn: 'full',
        },
        {
          name: 'environmentalLiabilities',
          label: 'Known Environmental Liabilities',
          type: 'textarea',
          required: true,
          placeholder: 'Describe any contamination, remediation obligations, violations...',
          helpText: 'Describe any known environmental issues or liabilities',
          gridColumn: 'full',
        },
        {
          name: 'reclamationPlan',
          label: 'Reclamation and Closure Plan',
          type: 'textarea',
          required: true,
          placeholder: 'Describe reclamation activities, timeline, expected costs...',
          helpText: 'Summary of reclamation plan and estimated costs',
          gridColumn: 'full',
        },
        {
          name: 'reclamationBond',
          label: 'Reclamation Bond ($)',
          type: 'number',
          required: true,
          placeholder: 'Ex: 15000000',
          helpText: 'Amount of reclamation bond or financial assurance required',
          gridColumn: '1',
        },
        {
          name: 'reclamationBondPosted',
          label: 'Bond Posted',
          type: 'select',
          required: true,
          options: [
            { value: 'yes', label: 'Yes - Full amount posted' },
            { value: 'partial', label: 'Partial - Some posted' },
            { value: 'no', label: 'No - Not yet required' },
          ],
          gridColumn: '2',
        },
      ],
    },

    // Item 1306 - Mineral Resource Estimates
    {
      title: 'Item 1306 - Mineral Resource Estimates',
      description: 'Mineral resource estimates in compliance with S-K 1300',
      fields: [
        {
          name: 'resourceEffectiveDate',
          label: 'Effective Date',
          type: 'date',
          required: true,
          helpText: 'Date of the mineral resource estimate',
          gridColumn: '1',
        },
        {
          name: 'resourceCutoffGrade',
          label: 'Cut-off Grade',
          type: 'text',
          required: true,
          placeholder: 'Ex: 0.15% Cu equivalent',
          helpText: 'Cut-off grade used for resource estimate',
          gridColumn: '2',
        },
        {
          name: 'resourceMeasured',
          label: 'Measured Resources',
          type: 'textarea',
          required: false,
          placeholder: 'Ex: 50 Mt @ 0.35% Cu, 0.01% Mo (175 kt Cu, 5 kt Mo)',
          helpText: 'Measured mineral resources (highest confidence): tonnage, grade, metal',
          gridColumn: 'full',
        },
        {
          name: 'resourceIndicated',
          label: 'Indicated Resources',
          type: 'textarea',
          required: true,
          placeholder: 'Ex: 150 Mt @ 0.30% Cu, 0.008% Mo (450 kt Cu, 12 kt Mo)',
          helpText: 'Indicated mineral resources (moderate confidence): tonnage, grade, metal',
          gridColumn: 'full',
        },
        {
          name: 'resourceInferred',
          label: 'Inferred Resources',
          type: 'textarea',
          required: false,
          placeholder: 'Ex: 75 Mt @ 0.25% Cu, 0.006% Mo (188 kt Cu, 4.5 kt Mo)',
          helpText: 'Inferred mineral resources (low confidence): tonnage, grade, metal',
          gridColumn: 'full',
        },
        {
          name: 'estimationMethod',
          label: 'Estimation Method',
          type: 'textarea',
          required: true,
          placeholder: 'Ex: Ordinary kriging with 25m x 25m x 15m blocks...',
          helpText: 'Method used (kriging, inverse distance, etc.) with parameters',
          gridColumn: 'full',
        },
        {
          name: 'databaseQuality',
          label: 'Database Quality',
          type: 'textarea',
          required: true,
          placeholder: 'Describe drill hole database, QA/QC, sample preparation...',
          helpText: 'Description of data quality, QA/QC procedures',
          gridColumn: 'full',
        },
      ],
    },

    // Item 1307 - Modifying Factors
    {
      title: 'Item 1307 - Modifying Factors',
      description: 'Factors used to convert resources to reserves',
      fields: [
        {
          name: 'miningMethod',
          label: 'Mining Method',
          type: 'select',
          required: true,
          options: [
            { value: 'open_pit', label: 'Open Pit' },
            { value: 'underground', label: 'Underground' },
            { value: 'combination', label: 'Combination (Open Pit + Underground)' },
            { value: 'solution', label: 'Solution Mining / In-Situ Leaching' },
          ],
          gridColumn: '1',
        },
        {
          name: 'miningRecovery',
          label: 'Mining Recovery (%)',
          type: 'number',
          required: true,
          placeholder: 'Ex: 95',
          helpText: 'Estimated mining recovery factor',
          gridColumn: '2',
        },
        {
          name: 'dilution',
          label: 'Dilution (%)',
          type: 'number',
          required: true,
          placeholder: 'Ex: 5',
          helpText: 'Estimated dilution factor from waste',
          gridColumn: '1',
        },
        {
          name: 'mineLife',
          label: 'Estimated Mine Life (years)',
          type: 'number',
          required: true,
          placeholder: 'Ex: 15',
          helpText: 'Projected mine life in years',
          gridColumn: '2',
        },
        {
          name: 'processingMethod',
          label: 'Processing Method',
          type: 'textarea',
          required: true,
          placeholder: 'Describe crushing, grinding, flotation, leaching, etc...',
          helpText: 'Description of ore processing method and flowsheet',
          gridColumn: 'full',
        },
        {
          name: 'processingRecovery',
          label: 'Processing Recovery (%)',
          type: 'number',
          required: true,
          placeholder: 'Ex: 87.5',
          helpText: 'Estimated metallurgical recovery',
          gridColumn: '1',
        },
        {
          name: 'processingCapacity',
          label: 'Processing Capacity (tpd)',
          type: 'number',
          required: true,
          placeholder: 'Ex: 45000',
          helpText: 'Tonnes per day processing capacity',
          gridColumn: '2',
        },
      ],
    },

    // Item 1308 - Mineral Reserve Estimates
    {
      title: 'Item 1308 - Mineral Reserve Estimates',
      description: 'Mineral reserve estimates (economically mineable)',
      fields: [
        {
          name: 'hasReserves',
          label: 'Reserves Declared?',
          type: 'select',
          required: true,
          options: [
            { value: 'yes', label: 'Yes' },
            { value: 'no', label: 'No - Exploration/Development stage' },
          ],
          gridColumn: '1',
        },
        {
          name: 'reserveEffectiveDate',
          label: 'Reserve Effective Date',
          type: 'date',
          required: false,
          helpText: 'Date of the mineral reserve estimate',
          gridColumn: '2',
        },
        {
          name: 'reserveProven',
          label: 'Proven Reserves',
          type: 'textarea',
          required: false,
          placeholder: 'Ex: 40 Mt @ 0.38% Cu, 0.011% Mo (152 kt Cu, 4.4 kt Mo)',
          helpText: 'Proven mineral reserves (highest confidence, economically viable)',
          gridColumn: 'full',
        },
        {
          name: 'reserveProbable',
          label: 'Probable Reserves',
          type: 'textarea',
          required: false,
          placeholder: 'Ex: 120 Mt @ 0.32% Cu, 0.009% Mo (384 kt Cu, 10.8 kt Mo)',
          helpText: 'Probable mineral reserves (lower confidence, economically viable)',
          gridColumn: 'full',
        },
      ],
    },

    // Item 1309 - Capital and Operating Costs
    {
      title: 'Item 1309 - Capital and Operating Costs',
      description: 'Estimated capital and operating costs',
      fields: [
        {
          name: 'initialCapex',
          label: 'Initial Capital (CAPEX) ($M)',
          type: 'number',
          required: true,
          placeholder: 'Ex: 450',
          helpText: 'Estimated initial capital expenditure in millions',
          gridColumn: '1',
        },
        {
          name: 'sustainingCapex',
          label: 'Sustaining Capital ($M)',
          type: 'number',
          required: false,
          placeholder: 'Ex: 120',
          helpText: 'Estimated sustaining capital over mine life',
          gridColumn: '2',
        },
        {
          name: 'operatingCost',
          label: 'Operating Cost ($/ton mined)',
          type: 'number',
          required: true,
          placeholder: 'Ex: 12.50',
          helpText: 'Estimated operating cost per ton mined',
          gridColumn: '1',
        },
        {
          name: 'cashCost',
          label: 'All-in Cash Cost ($/lb or $/oz)',
          type: 'number',
          required: false,
          placeholder: 'Ex: 2.15',
          helpText: 'All-in sustaining cash cost per unit of production',
          gridColumn: '2',
        },
        {
          name: 'costBreakdown',
          label: 'Cost Breakdown',
          type: 'textarea',
          required: true,
          placeholder: 'Mining: $X, Processing: $Y, G&A: $Z, Royalties: $W...',
          helpText: 'Breakdown of operating costs by category',
          gridColumn: 'full',
        },
      ],
    },

    // Item 1310 - Economic Analysis
    {
      title: 'Item 1310 - Economic Analysis',
      description: 'Economic analysis and feasibility',
      fields: [
        {
          name: 'npv',
          label: 'Net Present Value (NPV) ($M)',
          type: 'number',
          required: true,
          placeholder: 'Ex: 850',
          helpText: 'NPV at specified discount rate (after-tax)',
          gridColumn: '1',
        },
        {
          name: 'discountRate',
          label: 'Discount Rate (%)',
          type: 'number',
          required: true,
          placeholder: 'Ex: 5',
          helpText: 'Discount rate used for NPV calculation',
          gridColumn: '2',
        },
        {
          name: 'irr',
          label: 'Internal Rate of Return (IRR) (%)',
          type: 'number',
          required: true,
          placeholder: 'Ex: 18.5',
          helpText: 'Project internal rate of return (after-tax)',
          gridColumn: '1',
        },
        {
          name: 'paybackPeriod',
          label: 'Payback Period (years)',
          type: 'number',
          required: true,
          placeholder: 'Ex: 4.2',
          helpText: 'Estimated payback period',
          gridColumn: '2',
        },
        {
          name: 'commodityPrice',
          label: 'Commodity Price Assumption',
          type: 'text',
          required: true,
          placeholder: 'Ex: $3.50/lb Cu, $15/lb Mo, $1,800/oz Au',
          helpText: 'Metal price assumptions used in economic analysis',
          gridColumn: 'full',
        },
        {
          name: 'sensitivityAnalysis',
          label: 'Sensitivity Analysis',
          type: 'textarea',
          required: true,
          placeholder: 'NPV sensitivity: +10% grade = $X, -20% opex = $Y, $4.00/lb Cu = $Z...',
          helpText: 'Summary of sensitivity to key variables (price, grade, costs)',
          gridColumn: 'full',
        },
        {
          name: 'economicRisks',
          label: 'Economic Risks',
          type: 'textarea',
          required: true,
          placeholder: 'Commodity price volatility, permitting delays, cost overruns...',
          helpText: 'Key economic risks and uncertainties',
          gridColumn: 'full',
        },
      ],
    },

    // Qualified Person Declaration
    {
      title: 'Qualified Person Declaration (Item 1302(d))',
      description: 'Qualified Person(s) responsible for technical report',
      fields: [
        {
          name: 'qualifiedPersonName',
          label: 'Qualified Person Name',
          type: 'text',
          required: true,
          placeholder: 'Ex: John Smith',
          helpText: 'Name of the qualified person (QP)',
          gridColumn: '1',
        },
        {
          name: 'qualifiedPersonTitle',
          label: 'QP Title and Affiliation',
          type: 'text',
          required: true,
          placeholder: 'Ex: Senior Mining Engineer, ABC Mining Consultants Inc.',
          helpText: 'Professional title and company affiliation',
          gridColumn: '2',
        },
        {
          name: 'qualifiedPersonCredentials',
          label: 'QP Credentials',
          type: 'text',
          required: true,
          placeholder: 'Ex: P.E. (Professional Engineer), State of Nevada #12345',
          helpText: 'Professional credentials: P.E., P.Geo., CPG, FAusIMM, etc.',
          gridColumn: 'full',
        },
        {
          name: 'qualifiedPersonExperience',
          label: 'QP Relevant Experience',
          type: 'textarea',
          required: true,
          placeholder: 'Describe 5+ years experience with similar deposits, mining methods...',
          helpText: 'Summary of relevant experience (minimum 5 years)',
          gridColumn: 'full',
        },
        {
          name: 'qualifiedPersonIndependence',
          label: 'QP Independence',
          type: 'select',
          required: true,
          options: [
            { value: 'independent', label: 'Independent - No relationship with registrant' },
            { value: 'employee', label: 'Employee of Registrant' },
            { value: 'related', label: 'Related Party' },
          ],
          helpText: 'SEC requires disclosure of any relationship with registrant',
          gridColumn: 'full',
        },
        {
          name: 'qualifiedPersonConsent',
          label: 'QP Consent',
          type: 'select',
          required: true,
          options: [
            { value: 'yes', label: 'Yes - Written consent obtained' },
            { value: 'pending', label: 'Pending' },
          ],
          helpText: 'QP must consent to inclusion of technical information',
          gridColumn: '1',
        },
      ],
    },
  ],
};
