name: "🚀 Deploy to Render"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Trigger Render Deployment"
    runs-on: ubuntu-latest

    steps:
      - name: "🧩 Checkout repository"
        uses: actions/checkout@v4

      - name: "🧠 Show Git info"
        run: |
          echo "✅ Branch: ${{ github.ref }}"
          echo "✅ Commit: ${{ github.sha }}"
          echo "✅ Actor: ${{ github.actor }}"
          echo "✅ Repository: ${{ github.repository }}"

      - name: "🚀 Trigger Render deploy"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          echo "🔗 Triggering Render deploy..."
          if [ -z "$RENDER_DEPLOY_HOOK" ]; then
            echo "❌ ERROR: Secret RENDER_DEPLOY_HOOK is missing!"
            exit 1
          fi

          RESPONSE=$(curl -s -o /tmp/render_response.json -w "%{http_code}" -X POST "$RENDER_DEPLOY_HOOK")

          if [ "$RESPONSE" -eq 200 ] || [ "$RESPONSE" -eq 202 ]; then
            echo "✅ Deploy triggered successfully on Render!"
            cat /tmp/render_response.json
          else
            echo "❌ Failed to trigger Render deploy (HTTP $RESPONSE)"
            cat /tmp/render_response.json
            exit 1
          fi
